version: '2'
services:
    geckodriver:
        build: .
        environment:
            - VNC_ENABLED=true
            - EXPOSE_X11=true
        expose:
            - '4444'
            - '2828'
            - '5900'
        shm_size: 2g
        command: 'geckodriver --port=4444 --host 0.0.0.0 --log debug --marionette-port 2828'